version: '3.8'

services:
#  app:
#    build: .
#    ports:
#      - '8080:8080'
#    depends_on:
#      - db
#    environment:
#      - MONGO_URI=mongodb://db:27017

  db:
    image: mongo:4.4
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
